# Generated by Django 3.2.9 on 2021-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='board/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('write_day', models.DateTimeField(blank=True)),
                ('modify_day', models.DateTimeField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
