# Generated by Django 3.2.9 on 2021-11-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/static/upload'),
        ),
    ]
