# Generated by Django 3.2.9 on 2021-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211114_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_model',
            name='api_emotion_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
