# Generated by Django 3.2.9 on 2021-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_model_api_emotion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_model',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
