# Generated by Django 3.2.9 on 2021-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_model',
            name='api_emotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='board_model',
            name='auto_pick',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board_model',
            name='result_emotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='board_model',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board_model',
            name='weather',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
